language: go
sudo: required

go:
  - 1.7.x
  - 1.8.x
  - master

services:
  - rabbitmq

notifications:
    email: false

before_install:
    - make test.setup

script:
    - make test

matrix:
  allow_failures:
    - go: master
  fast_finish: true