language: go
sudo: required

go:
  - 1.8.x
  - master

services:
  - rabbitmq

notifications:
  email: false

install:
  - go get github.com/golang/dep/cmd/dep
  - dep ensure

script:
  - go test ./...

matrix:
  allow_failures:
    - go: master
  fast_finish: true