language: go
sudo: required

go:
  - 1.8.x
  - master

services:
  - rabbitmq

notifications:
  email: false

script:
  - make test.setup
  - make test
  - make build

matrix:
  allow_failures:
    - go: master
  fast_finish: true